default:
  SQLALCHEMY_DATABASE_URI: "someURL"

development:
  # Set to SQLite for local testing purposes
  SQLALCHEMY_DATABASE_URI: "sqlite:///test_python_database_can_be_deleted.db"

unittests:
  TESTING: True
  SQLALCHEMY_DATABASE_URI: "sqlite:///test_python_database_can_be_deleted.db"

integration:
  SQLALCHEMY_DATABASE_URI: "sqlite:////home/serviceuser/temp.db"

production:
  SQLALCHEMY_DATABASE_URI: "business_database:123456"
