name: Merge Requests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        args: ". --check"

    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
      run: |
        python -m pip install --upgrade pip setuptools
        pip install tox

    - name: Unit tests
      run: python -m tox -e integration

    - name: Integration tests
      run: python -m tox
